-- =============================================================================
-- Migration: 20260315000000_create_enums.sql
-- Purpose  : Define all application-level enum types used across the schema.
-- Affected : (no tables; only types)
-- Notes    : Enums must be created before any table that references them.
--            All enum values are lowercase and stable; adding new values
--            requires a separate ALTER TYPE migration.
-- =============================================================================

-- how a question was created: typed manually by a user or generated by ai
create
type generated_type_enum as enum ('manual', 'ai');

-- lifecycle state of a question:
--   active       – visible and usable in quiz sessions
--   flagged      – marked by the user as potentially incorrect
--   needs_review – automatically set when a user flags an attempt
--   verified     – manually confirmed as correct by the owner
--   archived     – hidden from sessions but retained for history
create
type question_status_enum as enum (
    'active',
    'flagged',
    'needs_review',
    'verified',
    'archived'
);

-- overall state of a training session
create
type session_status_enum as enum (
    'in_progress',
    'completed',
    'abandoned'
);

-- user's self-assessed result for a single quiz attempt
create
type attempt_verdict_enum as enum ('knew', 'did_not_know');